version: '3.7'

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local

services:
  mongo:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    restart: unless-stopped
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mern-exercice/backend:local
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - ./backend/:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - mongo
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: mern-exercice/frontend:local
    restart: unless-stopped
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
  proxy:
    image: nginx:1.21.0-alpine
    logging:
      options:
        max-size: "5m"
        max-file: "1"
    volumes:
      - ./proxy/cert/:/etc/nginx/cert
      - ./proxy/conf.d/mern-excercise.local.dev.conf:/etc/nginx/conf.d/mern-excercise.local.dev.conf
    ports:
      - 443:443
    expose:
      - "443"
    restart: unless-stopped
    depends_on:
      - mongo
      - backend
      - frontend
    networks:
      - app-network
